# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
    driver: "gd"

    filter_sets:
        thumb: 
            quality: 75
            filters: 
                thumbnail:
                    size: [200, 200]
                    mode: outbound
        logo:
            filters: 
                watermark_image:
                    # chemin vers le fichier
                    image: ../../src/watermark.png
                    # Taille relative de l'image
                    size: 0.5
                    # set the position of the watermark
                    position: bottomright
            

    # valid drivers options include "gd" or "gmagick" or "imagick"
    
