#!/bin/sh
rsync -av ./ aalshhs@ssh.cluster029.hosting.ovh.net:~/www/margauxBesson --include=public/build --include=public/.htaccess --exclude-from=.gitignore --exclude=".*" --exclude=".env"
ssh aalshhs@ssh.cluster029.hosting.ovh.net 'cd www/margauxBesson && php bin/console cache:clear'